# Generated by Django 5.1.7 on 2025-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='request_details',
            field=models.TextField(blank=True, null=True, verbose_name='Описание запроса'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='display_hours',
            field=models.BooleanField(default=False, verbose_name='Показывать часы практики в профиле'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='office_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Место/Формат работы'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='total_hours_worked',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего часов практики'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Мужчина'), ('FEMALE', 'Женщина'), ('OTHER', 'Другое'), ('UNKNOWN', 'Не указан')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('THERAPIST', 'Therapist'), ('ADMIN', 'Admin')], default='CLIENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Лет опыта'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='therapists', to='api.language', verbose_name='Языки'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='interested_topics',
            field=models.ManyToManyField(blank=True, related_name='interested_clients', to='api.skill', verbose_name='Интересующие темы/запросы'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='therapists', to='api.skill', verbose_name='Навыки/Специализации'),
        ),
    ]
