# Generated by Django 5.1.7 on 2025-04-16 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_language_skill_remove_therapistprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='Профиль LinkedIn'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='video_intro_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео-визитку'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Личный сайт'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='publication_images/', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TherapistPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='therapist_photos/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.therapistprofile', verbose_name='Профиль психолога')),
            ],
            options={
                'verbose_name': 'Фотография психолога',
                'verbose_name_plural': 'Фотографии психологов',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
