# Generated by Django 5.1.7 on 2025-04-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_therapistprofile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(db_index=True, editable=False, null=True, unique=True),
        ),
    ]
