# Generated by Django 5.1.7 on 2025-04-26 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_public_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='video_intro_url',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='website_url',
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Фотогалерея (массив URL)'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='short_video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL видеовизитки'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('STUDENT_1', 'Студент 1 ступени'), ('GRADUATE_1', 'Выпускник 1 ступени'), ('STUDENT_2', 'Студент 2 ступени'), ('GRADUATE_2', 'Выпускник 2 ступени')], max_length=20, null=True, verbose_name='Статус обучения/практики'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Обращение (напр. she/her)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='therapistphoto',
            name='therapist_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='api.therapistprofile', verbose_name='Профиль психолога'),
        ),
    ]
