# Generated by Django 5.1.7 on 2025-04-26 00:44

import uuid
from django.db import migrations, models


def populate_uuid(apps, schema_editor):
    Publication = apps.get_model('api', 'Publication')
    for pub in Publication.objects.all():
        pub.uuid_id_temp = uuid.uuid4() 
        pub.save(update_fields=['uuid_id_temp'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]


    operations = [
        migrations.AddField(
            model_name='publication',
            name='uuid_id_temp',
            field=models.UUIDField(null=True, unique=True),  # Уникальное, но nullable
        ),
        migrations.RunPython(populate_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='publication',
            name='uuid_id_temp',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),  # Ставим default для будущих
        ),
        migrations.RemoveField(
            model_name='publication',
            name='id',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='uuid_id_temp',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ] 