# Generated by Django 5.1.7 on 2025-04-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_publication_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='is_published',
        ),
    ]
