# Generated by Django 5.1.7 on 2025-04-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_populate_user_public_id'),
        ('api', '0007_remove_publication_is_published'),
    ]

    operations = [
    ]
