# Generated by Django 5.1.7 on 2025-04-28 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20250426_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
